% this file is used to create and manage the DB_syndrome database.
if isdeployed
else
    addpath('/net/isi-software/tools/matlab_extools/matlab-sqlite3-driver');
    %addpath('/net/isi-backup/restricted/face/PROJECT/SQL_UPDATE/matlab-serialization-master/matlab-serialization-master');
    addpath('/net/isi-software/tools/matlab_extools/serialize/');
    addpath('/net/isi-backup/restricted/face/AAM_2013/functions');
end


fileID = fopen('var_database.txt','r');
var_database = fgets(fileID); % path to the image
cellStirng = breakString(var_database,'*');
var_database = cellStirng{1};

table1 = 'processing';
table1_content = {'processing_id' 'INTEGER PRIMARY KEY';...
    'meta_id' 'INTEGER';...
    'image_path' 'VARCHAR';...
    'image_name' 'VARCHAR';...
    'image_path_name' 'VARCHAR';...
    'image_date' 'VARCHAR';...
    %'image_content' 'BLOB';...
    'boolean_fland' 'INTEGER';...
    'fland' 'BLOB';...
    'aam' 'BLOB';...
    'boolean_belhumeur' 'INTEGER';...
    'boolean_success' 'INTEGER';...
    'boolean_badfit' 'INTEGER';...
    'belhumeur' 'BLOB'...
    };

table2 = 'meta';
table2_content = {'id' 'INTEGER PRIMARY KEY';...
    'gene' 'VARCHAR';...
    'patient_id' 'VARCHAR';...
    'DOB' 'VARCHAR';...
    'gender' 'VARCHAR';...
    'syndrome' 'VARCHAR';...
    'parent_father' 'INTEGER';...
    'parent_mother' 'INTEGER';...
    'boolean_parent' 'INTEGER'};
 %'image_path' 'VARCHAR';...
    %'image_name' 'VARCHAR';...

table3 = 'features';
table3_content = {
    'features_id' 'INTEGER PRIMARY KEY';...
    'processing_id' 'INTEGER';...
    'shape_9' 'BLOB';...
    'appearance_9_intensity' 'BLOB';...
    'appearance_9_gradient' 'BLOB';...
    'shape' 'BLOB';...
    'appearance_intensity' 'BLOB';...
    'appearance_gradient' 'BLOB'...
                    };

table4 = 'FS_features';
table4_content = {
    'FS_features_id' 'INTEGER PRIMARY KEY';...
    'processing_id' 'INTEGER';...
    'shape_pca' 'BLOB';...
    'appearance_intensity_pca' 'BLOB';...
    'appearance_gradient_pca' 'BLOB';...
    'shape_pca_lmnn' 'BLOB';...
    'appearance_intensity_pca_lmnn' 'BLOB';...
    'appearance_gradient_pca_lmnn' 'BLOB';...
    'fusion_intensity_pca_lmnn' 'BLOB';...
    'fusion_gradient_pca_lmnn' 'BLOB';...
    'shape_pca_lmnn_pca' 'BLOB';...
    'appearance_intensity_pca_lmnn_pca' 'BLOB';...
    'appearance_gradient_pca_lmnn_pca' 'BLOB';...
    'fusion_intensity_pca_lmnn_pca' 'BLOB';...
    'fusion_gradient_pca_lmnn_pca' 'BLOB';...
    
                    };

table5 = 'metrics';
table5_content = {
    'metrics_id' 'INTEGER PRIMARY KEY';...
    'meta_id' 'INTEGER';...
    'diag_hyp' 'BLOB';...
                    }; 

%delete(var_database)%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
sqlite3.open(var_database);

%tables = {table4};
%table_conts = {table4_content};

tables = {table1, table2, table3, table4, table5};
table_conts = {table1_content, table2_content, table3_content, table4_content, table5_content};

for k=1:numel(tables)
    table_specifications = '';
    for i=1:size(table_conts{k},1)-1
            table_specifications = [table_specifications, table_conts{k}{i,1}, ' ', table_conts{k}{i,2},','];
    end
    table_specifications = [table_specifications, table_conts{k}{end,1}, ' ', table_conts{k}{end,2}];
    sqlite3.execute(['CREATE TABLE ' tables{k} ' (' table_specifications ')']);
end 
% table_specifications = '';
% for i=1:size(table1_content,1)-1
%         table_specifications = [table_specifications, table1_content{i,1}, ' ', table1_content{i,2},','];
% end
% table_specifications = [table_specifications, table1_content{end,1}, ' ', table1_content{end,2}];
% sqlite3.execute(['CREATE TABLE ' table1 ' (' table_specifications ')']);
% 
% % use sqlite3.execute('ALTER TABLE records ADD newCol') to add a new field
% % in the table.
% 
% table_specifications = '';
% for i=1:size(table2_content,1)-1
%         table_specifications = [table_specifications, table2_content{i,1}, ' ', table2_content{i,2},','];
% end
% table_specifications = [table_specifications, table2_content{end,1}, ' ', table2_content{end,2}];
% sqlite3.execute(['CREATE TABLE ' table2 ' (' table_specifications ')']);


sqlite3.close();

if isdeployed
    exit;
end
